### ISSUE TITLE
Aggiunta file requirements.txt

### ISSUE THREAD

**Issue by edoardopigaiani** [Nicuz/Pyliad#1]
Per installare automagicamente le dipendenze puoi aggiungere al repo il file _requirements.txt_ così da poter dare _pip install -r requirements.txt_

La sintassi del file dovrebbe essere circa così:

> requests==2.18.4
> BeautifulSoup==3.2.1

Dovrebbe diventare tutto più veloce e più facile da mantenere (tipo che se la versione nuova di _requests_ rompe tutto puoi specificare la versione da installare) ;)

**Comment by Nicuz** [comment]
Fatto, grazie per il suggerimento!
